baseURL = "https://machard.github.io/linkedin-intelligence"
languageCode = "en-us"
theme = "gallerydeluxe"
title = "LinkedIn Intelligence"

[taxonomies]
category = "categories"
tag = "tags"

[params]
galleryDir = "content/gallery"
images = ["/glyph.png"]
description = "Resonant Signal"

[outputs]
home = ["HTML", "JSON"]
section = ["HTML", "JSON"]
