baseURL = "https://machard.github.io/linkedin-intelligence/"
languageCode = "en-us"
theme = "gallerydeluxe"
title = "Matthieu Achard — LinkedIn Intelligence"

[taxonomies]
category = "categories"
tag = "tags"

[params]
galleryDir = "content/gallery"
images = ["/glyph.png"]

[outputs]
home = ["HTML", "JSON"]
section = ["HTML", "JSON"]
